In [37]:
import numpy as np
import pandas as pd
import matplotlib as plt
from matplotlib.pyplot import subplots
from statsmodels.datasets import get_rdataset
import sklearn.model_selection as skm
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score
import numpy as np
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import log_loss
from scipy.stats import entropy
from sklearn.metrics import accuracy_score
from sklearn.tree import export_text
from sklearn.tree import plot_tree
from sklearn.model_selection import KFold, cross_val_score
from sklearn.metrics import mean_squared_error
from sklearn.impute import SimpleImputer
#from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import precision_score, recall_score, f1_score
from sklearn.metrics import balanced_accuracy_score, roc_auc_score, make_scorer


In [38]:
df = pd.read_csv("train.csv")
df.head()

Time in Business  report revenue  Operating Costs Variance  Number of NSFs  \
0                49        300000.0              1.624340e-01             0.0   
1               291        900000.0              3.670000e-16             0.0   
2               160       2500000.0                       NaN             NaN   
3                89        425500.0              5.335332e-01            17.0   
4                25       1000000.0                       NaN             NaN   

   Debt Count Last 3 Months  Debt Count Last 1 Month  \
0                       3.0                      2.0   
1                       4.0                      4.0   
2                       NaN                      NaN   
3                       3.0                      3.0   
4                       NaN                      NaN   

   New Debt Count Last 3 Months  New Debt Count Last 1 Month  \
0                           NaN                          0.0   
1                           NaN                          2.0   
2                           NaN                          NaN   
3                           1.0                          0.0   
4                           NaN                          NaN   

   Debt Count First Last 1 Month Diff  New Debt Amount Last 3 Months  ...  \
0                                 0.0                            NaN  ...   
1                                 2.0                            NaN  ...   
2                                 NaN                            NaN  ...   
3                                 2.0                            0.0  ...   
4                                 NaN                            NaN  ...   

   credit_InquiriesDuringLast6Months  credit_TotalTradeItems  \
0                               25.0                    51.0   
1                                2.0                    27.5   
2                                4.0                    28.0   
3                                9.0                    29.5   
4                               19.0                    57.0   

   credit_PaidAccounts  credit_SatisfactoryAccounts  \
0                 12.0                         51.0   
1                 14.0                         15.5   
2                 17.0                         27.0   
3                 11.5                         18.5   
4                 32.0                         54.0   

   credit_NowDelinquentDerog  credit_DelinquenciesOver60Days  \
0                        0.0                             0.0   
1                        2.0                             4.0   
2                        0.0                             0.0   
3                        7.5                             1.5   
4                        1.0                             0.0   

   credit_DelinquenciesOver90Days  credit_DerogCounter  experian_ownerscore  \
0                             0.0                  0.0                585.0   
1                             6.0                  4.5                  NaN   
2                             0.0                  2.0                715.0   
3                             2.5                 85.5                535.5   
4                             0.0                 26.0                664.0   

   default  
0        0  
1        0  
2        1  
3        1  
4        0  

[5 rows x 41 columns]

In [39]:
column_names = df.columns.tolist()
print("Column Names:", column_names)

Column Names: ['Time in Business', 'report revenue', 'Operating Costs Variance', 'Number of NSFs', 'Debt Count Last 3 Months', 'Debt Count Last 1 Month', 'New Debt Count Last 3 Months', 'New Debt Count Last 1 Month', 'Debt Count First Last 1 Month Diff', 'New Debt Amount Last 3 Months', 'New Debt Amount Last 1 Month', 'DSCR Last 6 to 3 Months', 'Operating Profit Margin Slope', 'DSCR Last 3 Months', 'tu_score', 'tu_revolvingAmount_creditLimit', 'tu_revolvingAmount_currentBalance', 'tu_revolvingAmount_pastDue', 'tu_revolvingAmount_monthlyPayment', 'tu_installmentAmount_highCredit', 'tu_installmentAmount_creditLimit', 'tu_installmentAmount_currentBalance', 'noOfNegativeBal', 'monthlyDeposits', 'inputMonthlyDeposits', 'noOfDeposits', 'monthlyWithdrawals', 'credit_RealEstatePaymentPartialFlag', 'credit_RevolvingAvailablePercent', 'credit_RevolvingAvailablePartialFlag', 'credit_TotalInquiries', 'credit_InquiriesDuringLast6Months', 'credit_TotalTradeItems', 'credit_PaidAccounts', 'credit_Sati

In [40]:
missing_values = df.isnull().sum()
print(missing_values)

Time in Business                           0
report revenue                             3
Operating Costs Variance                 781
Number of NSFs                           781
Debt Count Last 3 Months                 781
Debt Count Last 1 Month                  781
New Debt Count Last 3 Months             986
New Debt Count Last 1 Month              830
Debt Count First Last 1 Month Diff       830
New Debt Amount Last 3 Months            986
New Debt Amount Last 1 Month             830
DSCR Last 6 to 3 Months                  986
Operating Profit Margin Slope            831
DSCR Last 3 Months                       993
tu_score                                  86
tu_revolvingAmount_creditLimit           194
tu_revolvingAmount_currentBalance        194
tu_revolvingAmount_pastDue               194
tu_revolvingAmount_monthlyPayment        194
tu_installmentAmount_highCredit          393
tu_installmentAmount_creditLimit         393
tu_installmentAmount_currentBalance      393
noOfNegati

In [41]:
missing_counts_sorted = missing_values.sort_values(ascending=False)
print(missing_counts_sorted)

credit_RealEstatePaymentPartialFlag     1957
credit_RevolvingAvailablePartialFlag    1917
DSCR Last 3 Months                       993
New Debt Count Last 3 Months             986
New Debt Amount Last 3 Months            986
DSCR Last 6 to 3 Months                  986
Operating Profit Margin Slope            831
New Debt Count Last 1 Month              830
Debt Count First Last 1 Month Diff       830
New Debt Amount Last 1 Month             830
Operating Costs Variance                 781
Number of NSFs                           781
Debt Count Last 3 Months                 781
Debt Count Last 1 Month                  781
tu_installmentAmount_creditLimit         393
tu_installmentAmount_currentBalance      393
tu_installmentAmount_highCredit          393
tu_revolvingAmount_pastDue               194
tu_revolvingAmount_monthlyPayment        194
tu_revolvingAmount_currentBalance        194
tu_revolvingAmount_creditLimit           194
noOfNegativeBal                          190
monthlyDep

In [42]:
y=df['default'].copy()
y.head()

0    0
1    0
2    1
3    1
4    0
Name: default, dtype: int64

In [43]:
x=df.drop(columns='default',axis=1).copy() 
x.head()

Time in Business  report revenue  Operating Costs Variance  Number of NSFs  \
0                49        300000.0              1.624340e-01             0.0   
1               291        900000.0              3.670000e-16             0.0   
2               160       2500000.0                       NaN             NaN   
3                89        425500.0              5.335332e-01            17.0   
4                25       1000000.0                       NaN             NaN   

   Debt Count Last 3 Months  Debt Count Last 1 Month  \
0                       3.0                      2.0   
1                       4.0                      4.0   
2                       NaN                      NaN   
3                       3.0                      3.0   
4                       NaN                      NaN   

   New Debt Count Last 3 Months  New Debt Count Last 1 Month  \
0                           NaN                          0.0   
1                           NaN                          2.0   
2                           NaN                          NaN   
3                           1.0                          0.0   
4                           NaN                          NaN   

   Debt Count First Last 1 Month Diff  New Debt Amount Last 3 Months  ...  \
0                                 0.0                            NaN  ...   
1                                 2.0                            NaN  ...   
2                                 NaN                            NaN  ...   
3                                 2.0                            0.0  ...   
4                                 NaN                            NaN  ...   

   credit_TotalInquiries  credit_InquiriesDuringLast6Months  \
0                   59.0                               25.0   
1                    7.0                                2.0   
2                   16.0                                4.0   
3                   28.5                                9.0   
4                   33.0                               19.0   

   credit_TotalTradeItems  credit_PaidAccounts  credit_SatisfactoryAccounts  \
0                    51.0                 12.0                         51.0   
1                    27.5                 14.0                         15.5   
2                    28.0                 17.0                         27.0   
3                    29.5                 11.5                         18.5   
4                    57.0                 32.0                         54.0   

   credit_NowDelinquentDerog  credit_DelinquenciesOver60Days  \
0                        0.0                             0.0   
1                        2.0                             4.0   
2                        0.0                             0.0   
3                        7.5                             1.5   
4                        1.0                             0.0   

   credit_DelinquenciesOver90Days  credit_DerogCounter  experian_ownerscore  
0                             0.0                  0.0                585.0  
1                             6.0                  4.5                  NaN  
2                             0.0                  2.0                715.0  
3                             2.5                 85.5                535.5  
4                             0.0                 26.0                664.0  

[5 rows x 40 columns]

In [44]:
#selected_features = ["tu_installmentAmount_creditLimit",
#"tu_installmentAmount_currentBalance",      
#"tu_installmentAmount_highCredit",          
#"tu_revolvingAmount_pastDue",               
#"tu_revolvingAmount_monthlyPayment",        
#"tu_revolvingAmount_currentBalance",        
#"tu_revolvingAmount_creditLimit",
#"noOfNegativeBal",                          
#"monthlyDeposits",                          
#"inputMonthlyDeposits",                     
#"noOfDeposits",                             
#"monthlyWithdrawals",                       
#"experian_ownerscore",                      
#"tu_score",                                  
#"credit_RevolvingAvailablePercent",          
#"credit_TotalInquiries",                     
#"credit_InquiriesDuringLast6Months",         
#"credit_TotalTradeItems",                    
#"credit_PaidAccounts",                       
#"credit_SatisfactoryAccounts",               
#"credit_NowDelinquentDerog",                 
#"credit_DelinquenciesOver60Days",            
#"credit_DelinquenciesOver90Days",            
#"credit_DerogCounter",                       
#"report revenue"
                     
#]
#selected_data = df[selected_features]

#other_data = df.drop(selected_features, axis=1)


In [45]:
x = df.drop("default", axis=1)
y = df["default"]

In [46]:
imputer = SimpleImputer(strategy='mean')

x_imputed = imputer.fit_transform(x)

In [47]:
missing_values = pd.DataFrame(x_imputed).isnull().sum()
print(missing_values)

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
26    0
27    0
28    0
29    0
30    0
31    0
32    0
33    0
34    0
35    0
36    0
37    0
38    0
39    0
dtype: int64


In [48]:
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(x_imputed, y)







RandomForestClassifier(random_state=42)

In [49]:

proximity_matrix = rf_model.apply(x_imputed)
print(proximity_matrix)

[[182 339 465 ... 285 471 212]
 [307 226 121 ... 318 364 299]
 [421 464 448 ... 372 444 420]
 ...
 [ 15  34  12 ...   6  93  75]
 [107 141 143 ... 382 459 190]
 [ 93  87 289 ...  21 247 324]]


In [50]:
missing_indices = np.argwhere(np.isnan(x_imputed))
print(missing_indices)

[]


In [51]:
for idx in missing_indices:
    instance_idx, feature_idx = idx
    proximity_values = proximity_matrix[instance_idx]
    non_missing_indices = np.where(~np.isnan(x_imputed[:, feature_idx]))[0]
    imputed_value = np.sum(proximity_values[non_missing_indices] * x_imputed[non_missing_indices, feature_idx]) / np.sum(proximity_values[non_missing_indices])
    x_imputed[instance_idx, feature_idx] = imputed_value

In [52]:
missing_indices = np.argwhere(np.isnan(x_imputed))
print(missing_indices)

[]


In [53]:
x_train, x_test, y_train, y_test = train_test_split(x_imputed, y, test_size =0.2, random_state=42)


In [54]:
rf_classifier = RandomForestClassifier(random_state=42)
param_grid = {
    'n_estimators': [100,200],
    'max_depth': [3,5,10],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

In [55]:
rf_classifier = RandomForestClassifier(random_state=42)
grid_search = GridSearchCV(estimator=rf_classifier, param_grid=param_grid, scoring='roc_auc', cv=3)
grid_search.fit(x_train, y_train)

best_params = grid_search.best_params_
print("Best Hyperparameters:", best_params)


Best Hyperparameters: {'max_depth': 10, 'min_samples_leaf': 4, 'min_samples_split': 2, 'n_estimators': 200}


In [56]:
rf = RandomForestClassifier(random_state=42,max_depth= 10, min_samples_leaf= 2, min_samples_split= 4, n_estimators= 200)
rf.fit(x_train, y_train)

RandomForestClassifier(max_depth=10, min_samples_leaf=2, min_samples_split=4,
                       n_estimators=200, random_state=42)

In [24]:
#class_probs = rf.predict_proba(x_test)
#print(class_probs)

In [25]:
#threshold = 0.83

# Adjust predictions based on the threshold
#y_pred = (class_probs[:,0] < threshold).astype(int)

#print(y_pred)

In [26]:
y_probabilities = rf.predict_proba(x_test)[:, 1]

print(y_probabilities)

[0.08647649 0.32131064 0.21799197 0.17730252 0.25573302 0.14724324
 0.1707182  0.11842681 0.10421342 0.09301099 0.19348872 0.18712013
 0.09569806 0.1501968  0.10862407 0.14006286 0.15185874 0.09720854
 0.22873766 0.26341379 0.32190606 0.16439924 0.09407083 0.06664377
 0.25088869 0.22467985 0.07532031 0.31497588 0.13337323 0.0949285
 0.30820521 0.26155414 0.22765918 0.30050475 0.17055581 0.20332449
 0.07170384 0.28221446 0.26995492 0.07842489 0.10274601 0.10345144
 0.37382701 0.20448009 0.24830533 0.16126567 0.12634132 0.21565797
 0.17209232 0.15561319 0.11024275 0.28477812 0.2166186  0.20032122
 0.19626124 0.1174872  0.15572092 0.2700896  0.07228324 0.17297343
 0.11704286 0.43595642 0.2650133  0.07051217 0.18273105 0.19846391
 0.3883019  0.05915839 0.09245276 0.08462386 0.37007574 0.1070981
 0.06661511 0.1614338  0.0827115  0.32756282 0.15497684 0.13202214
 0.36137808 0.12016695 0.13874054 0.09179013 0.08693554 0.08305488
 0.12514394 0.09398166 0.12001353 0.10008703 0.15222321 0.088758

In [28]:
threshold_choices = np.linspace(0.05,0.2039, 1000)
best_f1 = None
best_threshold = None

for threshold in threshold_choices:
    y_pred = (y_probabilities > threshold).astype(int)
        #accuracy = accuracy_score(y_test, y_pred)

    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = 2 * (precision * recall) / (precision + recall + 1e-6)  # F1-score
    
    if best_f1 is None or f1 > best_f1:
        best_f1 = f1
        best_threshold = threshold
        print(f"Threshold: {best_threshold:.4f}")
        print(f"Precision: {precision:.4f}, Recall: {recall:.4f}, F1-score: {best_f1:.4f}")
        print("=" * 40)

Threshold: 0.0500
Precision: 0.1802, Recall: 1.0000, F1-score: 0.3054
Threshold: 0.0508
Precision: 0.1807, Recall: 1.0000, F1-score: 0.3060
Threshold: 0.0518
Precision: 0.1811, Recall: 1.0000, F1-score: 0.3067
Threshold: 0.0574
Precision: 0.1816, Recall: 1.0000, F1-score: 0.3074
Threshold: 0.0580
Precision: 0.1821, Recall: 1.0000, F1-score: 0.3080
Threshold: 0.0592
Precision: 0.1825, Recall: 1.0000, F1-score: 0.3087
Threshold: 0.0596
Precision: 0.1830, Recall: 1.0000, F1-score: 0.3094
Threshold: 0.0602
Precision: 0.1835, Recall: 1.0000, F1-score: 0.3100
Threshold: 0.0620
Precision: 0.1839, Recall: 1.0000, F1-score: 0.3107
Threshold: 0.0636
Precision: 0.1844, Recall: 1.0000, F1-score: 0.3114
Threshold: 0.0656
Precision: 0.1849, Recall: 1.0000, F1-score: 0.3121
Threshold: 0.0657
Precision: 0.1854, Recall: 1.0000, F1-score: 0.3128
Threshold: 0.0723
Precision: 0.1870, Recall: 0.9718, F1-score: 0.3136
Threshold: 0.0736
Precision: 0.1875, Recall: 0.9718, F1-score: 0.3144
Threshold: 0.0745
Pr

In [36]:
y_probabilities = rf.predict_proba(x_imputed)[:, 1]

#print(y_probabilities)



threshold_choices = np.linspace(0.1639,0.2, 1000)
best_f1 = None
best_threshold = None

for threshold in threshold_choices:
    y_pred = (y_probabilities > threshold).astype(int)
        #accuracy = accuracy_score(y_test, y_pred)

    precision = precision_score(y, y_pred)
    recall = recall_score(y, y_pred)
    f1 = 2 * (precision * recall) / (precision + recall + 1e-6)  # F1-score
    
    if best_f1 is None or f1 > best_f1:
        best_f1 = f1
        best_threshold = threshold
        print(f"Threshold: {best_threshold:.4f}")
        print(f"Precision: {precision:.4f}, Recall: {recall:.4f}, F1-score: {best_f1:.4f}")
        print("=" * 40)

Threshold: 0.1639
Precision: 0.5455, Recall: 0.9191, F1-score: 0.6846
Threshold: 0.1640
Precision: 0.5464, Recall: 0.9191, F1-score: 0.6853
Threshold: 0.1640
Precision: 0.5473, Recall: 0.9191, F1-score: 0.6861
Threshold: 0.1644
Precision: 0.5483, Recall: 0.9191, F1-score: 0.6868
Threshold: 0.1647
Precision: 0.5492, Recall: 0.9191, F1-score: 0.6876
Threshold: 0.1647
Precision: 0.5502, Recall: 0.9191, F1-score: 0.6883
Threshold: 0.1653
Precision: 0.5513, Recall: 0.9162, F1-score: 0.6884
Threshold: 0.1657
Precision: 0.5523, Recall: 0.9162, F1-score: 0.6891
Threshold: 0.1660
Precision: 0.5542, Recall: 0.9162, F1-score: 0.6906
Threshold: 0.1661
Precision: 0.5552, Recall: 0.9162, F1-score: 0.6914
Threshold: 0.1662
Precision: 0.5561, Recall: 0.9162, F1-score: 0.6921
Threshold: 0.1662
Precision: 0.5571, Recall: 0.9162, F1-score: 0.6929
Threshold: 0.1664
Precision: 0.5581, Recall: 0.9162, F1-score: 0.6937
Threshold: 0.1667
Precision: 0.5591, Recall: 0.9162, F1-score: 0.6944
Threshold: 0.1668
Pr

In [35]:
y_probabilities = rf.predict_proba(x_test)[:, 1]
threshold_choices = np.linspace(,0.1638, 1000)
best_f1 = None
best_threshold = None

for threshold in threshold_choices:
    y_pred = (y_probabilities > threshold).astype(int)
        #accuracy = accuracy_score(y_test, y_pred)

    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = 2 * (precision * recall) / (precision + recall + 1e-6)  # F1-score
    
    if best_f1 is None or f1 > best_f1:
        best_f1 = f1
        best_threshold = threshold
        print(f"Threshold: {best_threshold:.4f}")
        print(f"Precision: {precision:.4f}, Recall: {recall:.4f}, F1-score: {best_f1:.4f}")
        print("=" * 40)

Threshold: 0.1638
Precision: 0.2486, Recall: 0.6056, F1-score: 0.3525
Threshold: 0.1640
Precision: 0.2500, Recall: 0.6056, F1-score: 0.3539
Threshold: 0.1644
Precision: 0.2515, Recall: 0.6056, F1-score: 0.3554
Threshold: 0.1647
Precision: 0.2529, Recall: 0.6056, F1-score: 0.3568
Threshold: 0.1675
Precision: 0.2561, Recall: 0.5915, F1-score: 0.3574
Threshold: 0.1689
Precision: 0.2577, Recall: 0.5915, F1-score: 0.3590
Threshold: 0.1691
Precision: 0.2593, Recall: 0.5915, F1-score: 0.3605
Threshold: 0.1697
Precision: 0.2609, Recall: 0.5915, F1-score: 0.3621
